//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Text_Analyzer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileLinks
    {
        public int Id { get; set; }
    
        public virtual UploadedFiles UploadedFiles { get; set; }
        public virtual FilesToDownload FilesToDownload { get; set; }
    }
}
