//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Text_Analyzer.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextAnalyzerModelContainer : DbContext
    {
        public TextAnalyzerModelContainer()
            : base("name=TextAnalyzerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UploadedFiles> UploadedFilesSet { get; set; }
        public virtual DbSet<FilesToDownload> FilesToDownloadSet { get; set; }
        public virtual DbSet<FileLinks> FileLinksSet { get; set; }
    }
}
